version: '3'

services:
  carts-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carts-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_MONGODB_URI=mongodb://carts-db:27017/data
      - JAVA_OPTS=-javaagent:/jmx_prometheus_javaagent.jar=8080:/prometheus-jmx-config.yaml
    networks:
      - monitoring-net
    depends_on:
      - users-carts-mock
      - carts-db
    volumes:
      - ./jmx_agent:/jmx_prometheus_javaagent.jar:ro
      - ./prometheus-jmx-config.yaml:/prometheus-jmx-config.yaml:ro

  users-carts-mock:
    image: mockserver/mockserver
    container_name: users-carts-mock
    ports:
      - "1080:1080"
    networks:
      - monitoring-net
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/mock.json
    volumes:
      - ./mock-expectations.json:/config/mock.json

  carts-db:
    image: mongo:6
    container_name: carts-db
    ports:
      - "27017:27017"
    networks:
      - monitoring-net
    volumes:
      - mongo-data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts/:/etc/prometheus/alerts/:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_DEFAULT_THEME=light
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

networks:
  monitoring-net:
    driver: bridge

volumes:
  mongo-data:
  grafana-data:
